// cmdmeta.go holds per-command full descriptions and option help text.
// These mirror the Python Click CLI output for golden-file parity testing.
package main

// commandFullDesc provides the full first-paragraph description for each command,
// matching the Python CLI's Click help text exactly.
var commandFullDesc = map[string]string{
	"audit":    "Scan installed packages for hidden Unicode characters",
	"cache":    "Manage the local package cache",
	"compile":  "Compile APM context into distributed AGENTS.md files",
	"config":   "Configure APM CLI",
	"deps":     "Manage APM package dependencies",
	"experimental": "Manage experimental feature flags",
	"init":     "Initialize a new APM project",
	"install":  "Install APM and MCP dependencies (supports APM packages, Claude skills\n(SKILL.md), and plugin collections (plugin.json); auto-creates apm.yml; use\n--allow-insecure for http:// packages)",
	"list":     "List available scripts in the current project",
	"marketplace": "Manage marketplaces for discovery and governance",
	"mcp":      "Discover, inspect, and install MCP servers",
	"outdated": "Show outdated locked dependencies",
	"pack":     "Pack distributable artifacts from your APM project.\n\nReads apm.yml to decide what to produce:\n\n  dependencies: block  ->  bundle (directory or .tar.gz)   marketplace:\n  block   ->  selected marketplace artifacts   both blocks present  ->\n  bundle plus selected marketplace artifacts\n\nThe lockfile (apm.lock.yaml) pins bundle contents. An enriched copy is\nembedded in each bundle.\n\nExamples:\n\n  # Bundle only (most common -- just dependencies: in apm.yml):   apm pack\n  # Claude Code plugin (default)   apm pack --target claude --archive   apm\n  pack --format apm -o ./dist       # Legacy APM bundle layout\n\n  # Marketplace only (marketplace: in apm.yml, no dependencies:):   apm pack\n  apm pack --offline --dry-run\n\n  # Both (apm.yml has dependencies: AND marketplace: blocks):   apm pack\n  apm pack --archive --offline\n\n  # Marketplace output paths are normally configured in apm.yml:   #\n  marketplace.claude.output / marketplace.codex.output\n\nExit codes:   0  Success   1  Build or runtime error   2  Manifest schema\nvalidation error   3  Version alignment check failed (--check-versions)   4\nMarketplace working-tree drift detected (--check-clean)",
	"plugin":   "Scaffold and manage plugins (plugin-author workflows)",
	"policy":   "Inspect and diagnose APM policy",
	"preview":  "Preview a script's compiled prompt files",
	"prune":    "Remove APM packages not listed in apm.yml",
	"run":      "Run a script with parameters (experimental)",
	"runtime":  "Manage AI runtimes (experimental)",
	"search":   "Search plugins in a marketplace (QUERY@MARKETPLACE)",
	"self-update": "Update the APM CLI binary itself to the latest version",
	"targets":  "Show resolved targets for the current project. If APM detects a target you\ndon't intend (e.g. CLAUDE.md is documentation, not a Claude Code config),\npin your targets explicitly in apm.yml.",
	"uninstall": "Remove APM packages, their integrated files, and apm.yml entries",
	"unpack":   "[Deprecated] Extract an APM bundle into the current project. Use 'apm\ninstall <bundle-path>' instead -- this command will be removed in v0.14.",
	"update":   "Refresh APM dependencies to the latest matching refs",
	"view": "View package metadata or list remote versions.\n\nWithout FIELD, displays local metadata for an installed package. With FIELD,\nqueries specific data (may contact the remote).\n\nFields:\n    versions    List available remote tags and branches\n\nExamples:\n    apm view org/repo                # Local metadata\n    apm view org/repo versions       # Remote tags/branches\n    apm view org/repo -g             # From user scope",
}

// commandOptions provides key options for each command, matching Python CLI help.
// Each entry includes the --help line with correct alignment (matching Click's output).
var commandOptions = map[string][]string{
	"compile": {
		"  -o, --output TEXT               Output file path (for single-file mode)",
		"  -t, --target TARGET             Target platform (comma-separated). Values:",
		"                                  copilot, claude, cursor, opencode, codex,",
		"                                  gemini, windsurf, agent-skills, all. 'agent-",
		"                                  skills' deploys to .agents/skills/ (cross-",
		"                                  client). 'all' = copilot+claude+cursor+openc",
		"                                  ode+codex+gemini+windsurf (excludes agent-",
		"                                  skills); combine with 'agent-skills' for",
		"                                  both.",
		"  --dry-run                       Preview compilation without writing files",
		"                                  (shows placement decisions)",
		"  --no-links                      Skip markdown link resolution",
		"  --chatmode TEXT                 Chatmode to prepend to AGENTS.md files",
		"  --watch                         Auto-regenerate on changes",
		"  --validate                      Validate primitives without compiling",
		"  --with-constitution / --no-constitution",
		"                                  Include Spec Kit constitution block at top",
		"                                  if memory/constitution.md present  [default:",
		"                                  with-constitution]",
		"  --single-agents                 Force single-file compilation (legacy mode)",
		"  -v, --verbose                   Show detailed source attribution and",
		"                                  optimizer analysis",
		"  --local-only                    Ignore dependencies, compile only local",
		"                                  primitives",
		"  --clean                         Remove orphaned AGENTS.md files that are no",
		"                                  longer generated",
		"  --legacy-skill-paths            Deploy skill files to per-client paths (e.g.",
		"                                  .cursor/skills/) instead of the shared",
		"                                  .agents/skills/ directory. Compatibility",
		"                                  flag for projects that need per-client skill",
		"                                  layouts.",
		"  --all                           Compile for all canonical targets.",
		"                                  Equivalent to --target all.",
		"  --help                          Show this message and exit.",
	},
	"install": {
		"  --runtime TEXT                  Target specific runtime only (copilot,",
		"                                  codex, vscode, cursor, opencode, gemini,",
		"                                  claude, windsurf)",
		"  --exclude TEXT                  Exclude specific runtime from installation",
		"  --only [apm|mcp]                Install only specific dependency type",
		"  --update                        Update dependencies to latest Git references",
		"                                  (deprecated: prefer 'apm update' for an",
		"                                  interactive plan, or 'apm update --yes' for",
		"                                  CI)",
		"  --dry-run                       Show what would be installed without",
		"                                  installing",
		"  --force                         Overwrite locally-authored files on",
		"                                  collision and deploy despite critical",
		"                                  security findings (does NOT refresh refs;",
		"                                  use 'apm update' for that)",
		"  --frozen                        Refuse to install when apm.lock.yaml is",
		"                                  missing or out of sync with apm.yml (CI-",
		"                                  safe; mutually exclusive with --update).",
		"                                  Structural presence check only; use 'apm",
		"                                  audit' for on-disk integrity.",
		"  -v, --verbose                   Show detailed installation information",
		"  --trust-transitive-mcp          Trust self-defined MCP servers from",
		"                                  transitive packages (skip re-declaration",
		"                                  requirement)",
		"  --parallel-downloads INTEGER    Max concurrent package downloads (0 to",
		"                                  disable parallelism)  [default: 4]",
		"  --dev                           Install as development dependency",
		"                                  (devDependencies)",
		"  -t, --target TARGET             Target harness(es) to deploy to. Comma-",
		"                                  separated for multiple: --target",
		"                                  claude,cursor. Repeating the flag (e.g. '-t",
		"                                  a -t b') is NOT supported -- only the last",
		"                                  value wins; use commas. Highest-priority",
		"                                  entry in the resolution chain (--target >",
		"                                  apm.yml targets: > auto-detect). Values:",
		"                                  copilot, claude, cursor, opencode, codex,",
		"                                  gemini, windsurf, agent-skills, all. 'agent-",
		"                                  skills' deploys to .agents/skills/ (cross-",
		"                                  client). 'all' = copilot+claude+cursor+openc",
		"                                  ode+codex+gemini+windsurf (excludes agent-",
		"                                  skills); combine with 'agent-skills' for",
		"                                  both. 'copilot-cowork' is also accepted when",
		"                                  the copilot-cowork experimental flag is",
		"                                  enabled (run 'apm experimental enable",
		"                                  copilot-cowork'). 'copilot-app' is also",
		"                                  accepted when the copilot-app experimental",
		"                                  flag is enabled (run 'apm experimental",
		"                                  enable copilot-app'). Note: '--target all'",
		"                                  on 'apm compile' is deprecated; use 'apm",
		"                                  compile --all' instead.",
		"  --allow-insecure                Allow HTTP (insecure) dependencies. Required",
		"                                  when dependencies use http:// URLs.",
		"  --allow-insecure-host HOSTNAME  Allow transitive HTTP (insecure)",
		"                                  dependencies from this hostname. Repeat for",
		"                                  multiple hosts.",
		"  -g, --global                    Install to user scope (~/.apm/) instead of",
		"                                  the current project. MCP servers target",
		"                                  global-capable runtimes only (Copilot CLI,",
		"                                  Codex CLI).",
		"  --ssh                           Prefer SSH transport for shorthand",
		"                                  (owner/repo) dependencies. Mutually",
		"                                  exclusive with --https.",
		"  --https                         Prefer HTTPS transport for shorthand",
		"                                  (owner/repo) dependencies. Mutually",
		"                                  exclusive with --ssh.",
		"  --allow-protocol-fallback       Restore the legacy permissive cross-protocol",
		"                                  fallback chain (escape hatch for migrating",
		"                                  users; also: APM_ALLOW_PROTOCOL_FALLBACK=1).",
		"                                  Caveat: fallback reuses the same port across",
		"                                  schemes; on servers that use different SSH",
		"                                  and HTTPS ports, omit this flag and pin the",
		"                                  dependency with an explicit ssh:// or",
		"                                  https:// URL.",
		"  --mcp NAME                      Add an MCP server entry to apm.yml. Use with",
		"                                  --transport, --url, --env, --header, --mcp-",
		"                                  version, or a stdio command after `--`.",
		"                                  Resolves active targets the same way `apm",
		"                                  install` does (--target > apm.yml targets: >",
		"                                  auto-detect); writes only for active",
		"                                  targets, skips others with [i].",
		"  --transport [stdio|http|sse|streamable-http]",
		"                                  MCP transport (stdio, http, sse, streamable-",
		"                                  http). Inferred from --url or post-- command",
		"                                  when omitted (requires --mcp).",
		"  --url TEXT                      MCP server URL for http/sse/streamable-http",
		"                                  transports (requires --mcp).",
		"  --env KEY=VALUE                 Environment variable for stdio MCP,",
		"                                  repeatable (requires --mcp).",
		"  --header KEY=VALUE              HTTP header for remote MCP, repeatable",
		"                                  (requires --mcp and --url).",
		"  --mcp-version TEXT              Pin MCP registry entry to a specific version",
		"                                  (requires --mcp).",
		"  --registry URL                  MCP registry URL (http:// or https://) for",
		"                                  resolving --mcp NAME. Overrides the",
		"                                  MCP_REGISTRY_URL env var. Default:",
		"                                  https://api.mcp.github.com. Captured in",
		"                                  apm.yml on the entry's 'registry:' field for",
		"                                  auditability. Not valid with --url or a",
		"                                  stdio command (self-defined entries).",
		"  --skill NAME                    Install only named skill(s) from a",
		"                                  SKILL_BUNDLE. Repeatable. Persisted in",
		"                                  apm.yml and apm.lock so bare 'apm install'",
		"                                  is deterministic. Use --skill '*' to reset",
		"                                  to all skills.",
		"  --no-policy                     Skip org policy enforcement for this",
		"                                  invocation. Does NOT bypass apm audit --ci.",
		"  --refresh                       Bypass the persistent cache and re-fetch all",
		"                                  dependencies from upstream.",
		"  --legacy-skill-paths            Deploy skill files to per-client paths (e.g.",
		"                                  .cursor/skills/) instead of the shared",
		"                                  .agents/skills/ directory. Compatibility",
		"                                  flag for projects that need per-client skill",
		"                                  layouts.",
		"  --as ALIAS                      Override the log/display label when",
		"                                  installing a local bundle (directory or",
		"                                  .tar.gz produced by 'apm pack'). Only valid",
		"                                  for local-bundle installs; passing --as",
		"                                  without a local bundle path is rejected.",
		"  --help                          Show this message and exit.",
	},
	"init": {
		"  -y, --yes        Skip interactive prompts and use auto-detected defaults",
		"  --plugin         (deprecated) Use 'apm plugin init' instead. Scaffolds",
		"                   plugin.json + apm.yml.",
		"  --marketplace    (deprecated) Use 'apm marketplace init' instead. Seeds a",
		"                   marketplace block.",
		"  --target TARGET  Comma-separated target list (skip prompt, write directly)",
		"  -v, --verbose    Show detailed output",
		"  --help           Show this message and exit.",
	},
	"update": {
		"  -y, --yes            Skip the confirmation prompt (for CI / automation)",
		"  --dry-run            Render the update plan and exit without changing",
		"                       anything",
		"  -v, --verbose        Show unchanged deps and detailed pipeline diagnostics",
		"  -t, --target TARGET  Agent target(s) to update for (e.g. claude, copilot,",
		"                       cursor, windsurf, codex, opencode, gemini). Comma-",
		"                       separated for multiple: --target claude,cursor.",
		"                       Highest-priority entry in the resolution chain",
		"                       (--target > apm.yml targets: > auto-detect).",
		"  --help               Show this message and exit.",
	},
	"audit": {
		"  --file PATH                     Scan an arbitrary file (not just APM-managed",
		"                                  files)",
		"  --strip                         Remove hidden characters from scanned files",
		"                                  (preserves emoji and whitespace)",
		"  -v, --verbose                   Show all findings including harmless ones",
		"  --dry-run                       Preview what --strip would remove without",
		"                                  modifying files",
		"  -f, --format [text|json|sarif|markdown]",
		"                                  Output format: text (default), json, sarif",
		"                                  (GitHub Code Scanning), markdown (step",
		"                                  summaries).",
		"  -o, --output PATH               Write output to file (auto-detects format",
		"                                  from extension: .sarif, .json, .md).",
		"  --ci                            Run lockfile consistency checks for CI/CD",
		"                                  gates. Exit 0 if clean, 1 if violations",
		"                                  found.",
		"  --policy TEXT                   Policy source. Accepts: 'org' (auto-discover",
		"                                  from your project's git remote),",
		"                                  'owner/repo' (defaults to github.com), an",
		"                                  https:// URL, or a local file path. Used",
		"                                  with --ci for policy checks. [experimental]",
		"  --no-cache                      Force fresh policy fetch (skip cache).",
		"  --no-policy                     Skip org policy discovery and enforcement.",
		"                                  Overridden when --policy is passed",
		"                                  explicitly.",
		"  --no-fail-fast                  Run all checks even after a failure",
		"                                  (default: stop at first failure).",
		"  --no-drift                      Skip the install-replay drift check. Reduces",
		"                                  coverage; use only for performance-",
		"                                  constrained CI loops.",
		"  --help                          Show this message and exit.",
	},
	"view": {
		"  -g, --global  Inspect package from user scope (~/.apm/)",
		"  --help        Show this message and exit.",
	},
	"search": {
		"  --limit INTEGER  Max results to show  [default: 20]",
		"  -v, --verbose    Show detailed output",
		"  --help           Show this message and exit.",
	},
	"uninstall": {
		"  --dry-run      Show what would be removed without removing",
		"  -v, --verbose  Show detailed removal information",
		"  -g, --global   Remove from user scope (~/.apm/) instead of the current",
		"                 project",
		"  --help         Show this message and exit.",
	},
	"unpack": {
		"  -o, --output PATH  Target directory (default: current directory).",
		"  --skip-verify      Skip bundle completeness check.",
		"  --dry-run          Show what would be unpacked without writing",
		"  --force            Deploy despite critical hidden-character findings.",
		"  -v, --verbose      Show detailed unpacking information",
		"  --help             Show this message and exit.",
	},
	"run": {
		"  -p, --param TEXT  Parameter in format name=value",
		"  -v, --verbose     Show detailed output",
		"  --help            Show this message and exit.",
	},
	"list": {
		"  --help  Show this message and exit.",
	},
	"targets": {
		"  --json  Output as JSON instead of a table.",
		"  --all   Include the agent-skills meta-target in JSON output (excluded by",
		"          default).",
		"  --help  Show this message and exit.",
	},
	"cache": {
		"  --help  Show this message and exit.",
	},
	"deps": {
		"  --help  Show this message and exit.",
	},
	"prune": {
		"  --dry-run  Show what would be removed without removing",
		"  --help     Show this message and exit.",
	},
	"self-update": {
		"  --check  Only check for updates without installing",
		"  --help   Show this message and exit.",
	},
	"preview": {
		"  -p, --param TEXT  Parameter in format name=value",
		"  -v, --verbose     Show detailed output",
		"  --help            Show this message and exit.",
	},
	"marketplace": {
		"  --help  Show this message and exit.",
	},
	"pack": {
		"  --format [plugin|apm]    Bundle format. 'plugin' (default) emits a Claude",
		"                           Code plugin directory with plugin.json. 'apm'",
		"                           produces the legacy APM bundle layout (kept for",
		"                           tooling that still consumes it).",
		"  -t, --target TARGET      [Deprecated] Target platform filter. Bundles are",
		"                           now target-agnostic; the consumer's project decides",
		"                           where files land at install time. Value is recorded",
		"                           in pack.target as informational metadata only and",
		"                           is ignored by 'apm install'. The flag will be",
		"                           removed in a future release.",
		"  --archive                Produce a .tar.gz archive instead of a directory.",
		"  -o, --output PATH        Bundle output directory (default: ./build).",
		"  --dry-run                Show what would be packed without writing",
		"  --force                  On collision (plugin format), last writer wins.",
		"  -v, --verbose            Show detailed packing information.",
		"  --offline                Marketplace: use cached refs, skip network.",
		"  --include-prerelease     Marketplace: include pre-release version tags.",
		"  --check-versions         Release gate: verify per-package versions agree",
		"                           with the configured marketplace.versioning.strategy",
		"                           (lockstep | tag_pattern | per_package). Exits 3 on",
		"                           misalignment. Composes with --check-clean and",
		"                           --dry-run.",
		"  --check-clean            Release gate: regenerate every configured",
		"                           marketplace output to a temp path and diff against",
		"                           the on-disk file. Exits 4 if the working tree is",
		"                           dirty (out-of-date marketplace.json). The gate",
		"                           itself never writes to disk.",
		"  -m, --marketplace TEXT   Comma-separated marketplace outputs to build (e.g.",
		"                           'claude,codex'). Use 'all' for every configured",
		"                           output, 'none' to skip marketplace. Default: build",
		"                           all configured outputs.",
		"  --marketplace-path TEXT  Override output path for a format: FORMAT=PATH",
		"                           (repeatable). Example: --marketplace-path",
		"                           claude=dist/marketplace.json",
		"  --json                   Emit machine-readable JSON to stdout; logs go to",
		"                           stderr.",
		"  --legacy-skill-paths     Deploy skill files to per-client paths (e.g.",
		"                           .cursor/skills/) instead of the shared",
		"                           .agents/skills/ directory. Compatibility flag for",
		"                           projects that need per-client skill layouts.",
		"  --help                   Show this message and exit.",
	},
}
