// cmdmeta.go holds per-command full descriptions and option help text.
// These mirror the Python Click CLI output for golden-file parity testing.
package main

// commandFullDesc provides the full first-paragraph description for each command,
// matching the Python CLI's Click help text exactly.
var commandFullDesc = map[string]string{
	"audit":    "Scan installed packages for hidden Unicode characters",
	"cache":    "Manage the local package cache",
	"compile":  "Compile APM context into distributed AGENTS.md files",
	"config":   "Configure APM CLI",
	"deps":     "Manage APM package dependencies",
	"experimental": "Manage experimental feature flags",
	"init":     "Initialize a new APM project",
	"install":  "Install APM and MCP dependencies (supports APM packages, Claude skills\n(SKILL.md), and plugin collections (plugin.json); auto-creates apm.yml; use\n--allow-insecure for http:// packages)",
	"list":     "List available scripts in the current project",
	"marketplace": "Manage marketplaces for discovery and governance",
	"mcp":      "Discover, inspect, and install MCP servers",
	"outdated": "Show outdated locked dependencies",
	"pack":     "Pack distributable artifacts from your APM project.",
	"plugin":   "Scaffold and manage plugins (plugin-author workflows)",
	"policy":   "Inspect and diagnose APM policy",
	"preview":  "Preview a script's compiled prompt files",
	"prune":    "Remove APM packages not listed in apm.yml",
	"run":      "Run a script with parameters (experimental)",
	"runtime":  "Manage AI runtimes (experimental)",
	"search":   "Search plugins in a marketplace (QUERY@MARKETPLACE)",
	"self-update": "Update the APM CLI binary itself to the latest version",
	"targets":  "Show resolved targets for the current project. If APM detects a target you\ndon't intend (e.g. CLAUDE.md is documentation, not a Claude Code config),\npin your targets explicitly in apm.yml.",
	"uninstall": "Remove APM packages, their integrated files, and apm.yml entries",
	"unpack":   "[Deprecated] Extract an APM bundle into the current project. Use 'apm\ninstall <bundle-path>' instead -- this command will be removed in v0.14.",
	"update":   "Refresh APM dependencies to the latest matching refs",
	"view": "View package metadata or list remote versions.\n\nWithout FIELD, displays local metadata for an installed package. With FIELD,\nqueries specific data (may contact the remote).\n\nFields:\n    versions    List available remote tags and branches\n\nExamples:\n    apm view org/repo                # Local metadata\n    apm view org/repo versions       # Remote tags/branches\n    apm view org/repo -g             # From user scope",
}

// commandOptions provides key options for each command, matching Python CLI help.
// Each entry includes the --help line with correct alignment (matching Click's output).
var commandOptions = map[string][]string{
	"compile": {
		"  -o, --output TEXT   Output file path (for single-file mode)",
		"  -t, --target TARGET Target platform (comma-separated)",
		"  --dry-run           Preview compilation without writing files",
		"  --no-links          Skip markdown link resolution",
		"  --watch             Auto-regenerate on changes",
		"  --validate          Validate primitives without compiling",
		"  --clean             Remove orphaned AGENTS.md files",
		"  --all               Compile for all canonical targets",
		"  -v, --verbose       Show detailed source attribution",
		"  --help              Show this message and exit.",
	},
	"install": {
		"  --runtime TEXT      Target specific runtime only",
		"  --exclude TEXT      Exclude specific runtime from installation",
		"  --only [apm|mcp]    Install only specific dependency type",
		"  --update            Update dependencies to latest Git references (deprecated)",
		"  --dry-run           Show what would be installed without installing",
		"  --force             Overwrite locally-authored files on collision",
		"  --frozen            Refuse to install when apm.lock.yaml is missing",
		"  -v, --verbose       Show detailed installation information",
		"  -t, --target TARGET Target harness(es) to deploy to",
		"  -g, --global        Install to user scope (~/.apm/)",
		"  --ssh               Prefer SSH transport for shorthand dependencies",
		"  --https             Prefer HTTPS transport for shorthand dependencies",
		"  --mcp NAME          Add an MCP server entry to apm.yml",
		"  --skill NAME        Install only named skill(s) from a SKILL_BUNDLE",
		"  --no-policy         Skip org policy enforcement for this invocation",
		"  --refresh           Bypass the persistent cache and re-fetch all dependencies",
		"  --dev               Install as development dependency",
		"  --allow-insecure    Allow HTTP (insecure) dependencies",
		"  --help              Show this message and exit.",
	},
	"init": {
		"  -y, --yes        Skip interactive prompts and use auto-detected defaults",
		"  --plugin         (deprecated) Use 'apm plugin init' instead. Scaffolds",
		"                   plugin.json + apm.yml.",
		"  --marketplace    (deprecated) Use 'apm marketplace init' instead. Seeds a",
		"                   marketplace block.",
		"  --target TARGET  Comma-separated target list (skip prompt, write directly)",
		"  -v, --verbose    Show detailed output",
		"  --help           Show this message and exit.",
	},
	"update": {
		"  -y, --yes            Skip the confirmation prompt (for CI / automation)",
		"  --dry-run            Render the update plan and exit without changing",
		"                       anything",
		"  -v, --verbose        Show unchanged deps and detailed pipeline diagnostics",
		"  -t, --target TARGET  Agent target(s) to update for (e.g. claude, copilot,",
		"                       cursor, windsurf, codex, opencode, gemini). Comma-",
		"                       separated for multiple: --target claude,cursor.",
		"                       Highest-priority entry in the resolution chain",
		"                       (--target > apm.yml targets: > auto-detect).",
		"  --help               Show this message and exit.",
	},
	"audit": {
		"  --file PATH                     Scan an arbitrary file (not just APM-managed",
		"                                  files)",
		"  --strip                         Remove hidden characters from scanned files",
		"                                  (preserves emoji and whitespace)",
		"  -v, --verbose                   Show all findings including harmless ones",
		"  --dry-run                       Preview what --strip would remove without",
		"                                  modifying files",
		"  -f, --format [text|json|sarif|markdown]",
		"                                  Output format: text (default), json, sarif",
		"                                  (GitHub Code Scanning), markdown (step",
		"                                  summaries).",
		"  -o, --output PATH               Write output to file (auto-detects format",
		"                                  from extension: .sarif, .json, .md).",
		"  --ci                            Run lockfile consistency checks for CI/CD",
		"                                  gates. Exit 0 if clean, 1 if violations",
		"                                  found.",
		"  --policy TEXT                   Policy source. Accepts: 'org' (auto-discover",
		"                                  from your project's git remote),",
		"                                  'owner/repo' (defaults to github.com), an",
		"                                  https:// URL, or a local file path. Used",
		"                                  with --ci for policy checks. [experimental]",
		"  --no-cache                      Force fresh policy fetch (skip cache).",
		"  --no-policy                     Skip org policy discovery and enforcement.",
		"                                  Overridden when --policy is passed",
		"                                  explicitly.",
		"  --no-fail-fast                  Run all checks even after a failure",
		"                                  (default: stop at first failure).",
		"  --no-drift                      Skip the install-replay drift check. Reduces",
		"                                  coverage; use only for performance-",
		"                                  constrained CI loops.",
		"  --help                          Show this message and exit.",
	},
	"view": {
		"  -g, --global  Inspect package from user scope (~/.apm/)",
		"  --help        Show this message and exit.",
	},
	"search": {
		"  --limit INTEGER  Max results to show  [default: 20]",
		"  -v, --verbose    Show detailed output",
		"  --help           Show this message and exit.",
	},
	"uninstall": {
		"  --dry-run      Show what would be removed without removing",
		"  -v, --verbose  Show detailed removal information",
		"  -g, --global   Remove from user scope (~/.apm/) instead of the current",
		"                 project",
		"  --help         Show this message and exit.",
	},
	"unpack": {
		"  -o, --output PATH  Target directory (default: current directory).",
		"  --skip-verify      Skip bundle completeness check.",
		"  --dry-run          Show what would be unpacked without writing",
		"  --force            Deploy despite critical hidden-character findings.",
		"  -v, --verbose      Show detailed unpacking information",
		"  --help             Show this message and exit.",
	},
	"run": {
		"  -p, --param TEXT  Parameter in format name=value",
		"  -v, --verbose     Show detailed output",
		"  --help            Show this message and exit.",
	},
	"list": {
		"  --help  Show this message and exit.",
	},
	"targets": {
		"  --json  Output as JSON instead of a table.",
		"  --all   Include the agent-skills meta-target in JSON output (excluded by",
		"          default).",
		"  --help  Show this message and exit.",
	},
	"cache": {
		"  --help  Show this message and exit.",
	},
	"deps": {
		"  --help  Show this message and exit.",
	},
	"config": {
		"  --help  Show this message and exit.",
	},
	"marketplace": {
		"  --help  Show this message and exit.",
	},
	"pack": {
		"  --dry-run          Show what would be packed without writing",
		"  -o, --output PATH  Bundle output directory (default: ./build).",
		"  --json             Emit machine-readable JSON to stdout.",
		"  -v, --verbose      Show detailed packing information.",
		"  --help             Show this message and exit.",
	},
}
